# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d0160047de4cc35fe73599ecc6dce076d79a0ae83c4d9b02867d3250e3bec00e984b52440020e098cfd4a3478f9c97ffb4cbaa2d5d66f198a307d4981607e7a

test:
  secret_key_base: e29b40cec2e38406415a391495daaa41120d9363815fff685709c7483ab97504eb3743dcdc8e1729a0bdccf275f1f3541eda6482efdfbfbfa69e250fbb4cdea0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
